# First rule
GET http://localhost.com/api/v1/products

# Second rule
GET http://localhost:3000/?q=[a,b,c]&l=Rust

# Third rule
GET https://google.com

# Headers
foo: bar
bar: baz
Content-Type: application/json
Authentication: Bearer <token>

{
    "foo": [ "fizz", "buzz" ]
}

# vim: ft=http
