name: format

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  dprint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Install dprint
        run: |
          curl -fsSL https://dprint.dev/install.sh | sh
          echo "/home/runner/.dprint/bin" >> "$GITHUB_PATH"

      - name: Run dprint
        run: dprint fmt

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: autoformat with dprint"
          branch: ${{ github.ref }}

      - name: Push formatted files
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
